# DevSkim security linting + SARIF upload
# Docs:
# - DevSkim Action: https://github.com/microsoft/DevSkim-Action
# - SARIF upload:   https://github.com/github/codeql-action/tree/main/upload-sarif

name: DevSkim

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '27 5 * * 6'  # Weekly, Sat 05:27 UTC

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write   # required to upload SARIF to code scanning

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: devskim-results.sarif
